# Generated by Django 3.2.7 on 2021-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon_and_dragons', models.CharField(max_length=150)),
                ('pathfinder', models.CharField(max_length=150)),
                ('roll20', models.CharField(max_length=150)),
                ('fantasy_grounds', models.CharField(max_length=150)),
            ],
        ),
    ]
