# Generated by Django 3.2.7 on 2021-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_cards', '0002_auto_20210917_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercards',
            name='character_image',
            field=models.ImageField(default='no', upload_to=''),
            preserve_default=False,
        ),
    ]
