# Generated by Django 3.2.7 on 2021-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_history',
            field=models.TextField(default='No', max_length=6000),
            preserve_default=False,
        ),
    ]
