# Generated by Django 3.2.7 on 2021-09-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gm',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='player',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='campaign_length',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='game_systems_looking_for',
            field=models.CharField(max_length=255),
        ),
    ]
