# Generated by Django 3.2.7 on 2021-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210917_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='looking_for_game',
            field=models.CharField(default='nno', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='gm',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='player',
            field=models.CharField(max_length=200),
        ),
    ]
