# Generated by Django 3.2.7 on 2021-10-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210928_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='party_leaders',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
