# Generated by Django 3.2.7 on 2021-10-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='chat_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
