# Generated by Django 3.2.7 on 2021-12-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lvl_of_rp',
            field=models.CharField(default='E', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.CharField(default='E', max_length=200),
            preserve_default=False,
        ),
    ]
